env:
  global:
    - secure: cS/5EzKw6WIuKuNIZptnVo7CtEci1ANpAHwpTKZo3fKrQKtR9ujininoWCZrRbjJMmmTNuLFV9iKGHE7NyhD0CY83mOEsfGWjvusFpI58MQHIxzzR4S/doEMcavc7uPl99UM6CaP0SrUyVZDxwyid31+uB2LpG6T4/i5x01IOv+7pMxHkHj5lx1k9pIcqPTZ1UEpQhbqkx7RQh9o+L9eoOLgpBabpELjaUNQ5ojBNPf6S3XPXcMJOYIJQZ3f2PoR2/opObHFy0cIOhszjLm4c9TCyP8/bw1XnZZOjCmFO6LCeas7pHbj6nktCJkk72JC+5134QHmT5VYQq7i8LLQBoHkdlSDLWOLLXj/RpP7Knm1JDKwZbo3eHVFyVuEA2dXz3Ze36UUSJD9WhG775YQAJAxxkCmrkzaccLfqHUHSnK5TgrrZxDP4rDNvXTqz/EEVrsSWXt/epE6bNm6dXtME7HXWQ2WVo9YkzAyf3JxVkQxTkIFcLummpuaf5NTbpYDzK0pB+vomac5nM47Iy65PvJ86QQH1b/6/5qZEdCPiHP7nNdc/urVAn8AeM0azGmYAaY28QZRLybkOLBTx3zIzsTUr5GI0okrt5NlWEaCwC9OITL+NOydwQIrhSKwr6wcGf0c6BuVpMjMuJF9f8w2R70BoY92V2UbKrb8v/FB1l4=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/dev-center
    - GIT_BRANCH: master

language: python
dist: xenial
sudo: required

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip3

install:
  - pip3 install --upgrade pip
  - pip3 install -r requirements.txt
  - pip3 install pylint

script:
  - pylint compare_with_upstream.py && python3 compare_with_upstream.py

notifications:
  on_success:   change
  on_failure:   always
